# This docker-compose is for development only.
# Run containers as host user 1000 (`id -u`) so php can write files to the host system

services:
  db:
    image: mariadb:latest
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: docker
      MARIADB_DATABASE: docker
      MARIADB_USER: docker
      MARIADB_PASSWORD: docker
    ports:
      - 3306:3306
  pw:
    depends_on:
      - db
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./site:/var/www/html/site
    ports:
      - 8080:80
    user: 1000:1000

volumes:
  dbdata: